### ISSUE TITLE
docker run failed

### ISSUE THREAD

**Issue by leigaoxiang** [zhang0jhon/AttentionOCR#4]
Hi：
when i perform nvidia-docker run --runtime=nvidia -p 5000:5000 -it zhang0jhon/demo:ocr bash

errors comes:
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/containerd/io.containerd.runtime.v1.linux/moby/1dd9d7b67a05f6c1b95ad52e6ada9b2ff3e9f249c85d214f405feb610c19b569/log.json: no such file or directory): fork/exec /usr/bin/nvidia-container-runtime: no such file or directory: : unknown.

thank you！

**Comment by zhang0jhon** [comment]
This may be caused by incorrect install of nvidia docker.

**Comment by Springzcf** [comment]
我运行docker，提示下面的错误
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short
然后我发现libcuda.so.430.14的大小是0;
lrwxrwxrwx 1 root root 12 Aug 28 02:42 /usr/lib/x86_64-linux-gnu/libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root 17 Aug 28 06:13 /usr/lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.430.14
-rwxr-xr-x 1 root root  0 Aug 28 02:42 /usr/lib/x86_64-linux-gnu/libcuda.so.418.56
-rwxr-xr-x 1 root root  0 Aug 28 06:13 /usr/lib/x86_64-linux-gnu/libcuda.so.430.14
这是什么原因呢？
不知道能不能提供cpu版本docker供学习，多谢了

**Comment by quuhua911** [comment]
I have the same problem.在docker下run 
python3 flaskapp.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flaskapp.py", line 17, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /usr/lib/x86_64-linux-gnu/libcuda.so.1: file too short


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Springzcf** [comment]
@quuhua911 你可以把代码从docker拷贝出来，再运行
