### ISSUE TITLE
按照步骤已得到训练模型，但是测试无法识别

### ISSUE THREAD

**Issue by shiyinzhi** [zhang0jhon/AttentionOCR#84]
张0jhon 您好，首先非常感谢您开源这个项目。通过训练已经得到了模型，但是在做test 的时候发现无法识别，是否是哪里出错了呢？

**Comment by xianzhe-741** [comment]
> 张0jhon 您好，首先非常感谢您开源这个项目。通过训练已经得到了模型，但是在做test 的时候发现无法识别，是否是哪里出错了呢？

请问你训练过程中有没有遇见过这个问题： - -！
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    train()
  File "train.py", line 64, in train
    starting_epoch=cfg.starting_epoch
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/config.py", line 119, in __init__
    assert_type(model, ModelDescBase, 'model')
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/train/config.py", line 107, in assert_type
    name, tp.__name__, v.__class__.__name__)
AssertionError: model has to be type 'ModelDescBase', but an object of type 'AttentionOCR' found.
